# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from protos.dish import dish_pb2 as protos_dot_dish_dot_dish__pb2


class DishStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetCircles = channel.unary_unary(
        '/dish.Dish/GetCircles',
        request_serializer=protos_dot_dish_dot_dish__pb2.Img_rgb.SerializeToString,
        response_deserializer=protos_dot_dish_dot_dish__pb2.Circles.FromString,
        )
    self.GetImg = channel.unary_unary(
        '/dish.Dish/GetImg',
        request_serializer=protos_dot_dish_dot_dish__pb2.Request.SerializeToString,
        response_deserializer=protos_dot_dish_dot_dish__pb2.Img_rgb.FromString,
        )


class DishServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetCircles(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetImg(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DishServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetCircles': grpc.unary_unary_rpc_method_handler(
          servicer.GetCircles,
          request_deserializer=protos_dot_dish_dot_dish__pb2.Img_rgb.FromString,
          response_serializer=protos_dot_dish_dot_dish__pb2.Circles.SerializeToString,
      ),
      'GetImg': grpc.unary_unary_rpc_method_handler(
          servicer.GetImg,
          request_deserializer=protos_dot_dish_dot_dish__pb2.Request.FromString,
          response_serializer=protos_dot_dish_dot_dish__pb2.Img_rgb.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'dish.Dish', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
